var lang = {
    ru: {
        mainScreenTitle1: "Накачайте ",
        mainScreenTitle2: "рельефный пресс ",
        mainScreenTitle3: "не выходя из дома",
        mainScreenSubtitle1: "с онлайн-курсом ",
        mainScreenSubtitle2: "на 30 дней",
        mainScreenBtn: "Попробовать",
        mainScreenBtnText1: "Первая неделя занятий ",
        mainScreenBtnText2: "всего за",
        mainScreenListSpan: "Если вы:",
        mainScreenListItem1: "Устали прятать пивной живот",
        mainScreenListItem2: "Мечтаете накачать жесткий пресс",
        mainScreenListItem3: "Желаете притягивать женские взгляды",
        mainScreenListItem4: "Хотите чувствовать себя увереннее",
        mainScreenListItem5: "Жаждите стать сильнее и выносливее",
        mainScreenSuptitle: "Онлайн-тренировки",
        mainScreenOnlineTitle: "“Рельефный пресс”",
        mainScreenOnlineSubtitle: "то, что вам надо!",
        profitTitle1: "Всего за ",
        profitTitle2: "30 дней",
        profitTitle3: " вы:",
        profitItemTitle1: "Улучшите свое самочувствие и настроение",
        profitItemText1: "Спорт положительно влияет на эмоциональное состояние человека и помогает вырабатывать гормоны радости",
        profitItemTitle2: "Станете более сильным и выносливым",
        profitItemText2: "Благодаря регулярным занятиям спортом вы заметите большие перемены в своей физической форме",
        profitItemTitle3: "Обретете красивый рельеф",
        profitItemText3: "Без толстой жировой прослойки, благодаря грамотному и комплексному подходу",
        profitItemTitle4: "Станете чувствовать себя увереннее",
        profitItemText4: "Благодаря эффектному виду, силе и вниманию противоположного пола ;)",
        profitPersonalTitle: "В личном кабинете вы найдете:",
        profitPersonalLabel: "Всё для топовых результатов!",
        profitPersonalItemText1: "Эффективные тренировки",
        profitPersonalItemText2: "Для заметных результатов",
        profitPersonalItemText3: "План питания на месяц",
        profitPersonalItemText4: "Для комплексного подхода",
        profitPersonalItemText5: "Советы и лекции от тренеров",
        profitPersonalItemText6: "Для подкованности и мотивации",
        tryTitle: "Накачайте жесткий пресс уже сейчас!",
        trySubtitle: "Попробуйте первую неделю тренировок всего за",
        tryBtn: "Попробовать",
        startTitle1: "Сейчас – ",
        startTitle2: "лучшее время, ",
        startTitle3: "чтобы начать!",
        startStepTitle1: "Оплатите доступ к курсу",
        startStepTitle2: "Войдите в личный кабинет",
        startStepTitle3: "Занимайтесь в любое время, в любом месте",
        startStepTitle4: "Кайфуйте от результатов и ловите восхищенные женские взгляды",
        orderSubtitle: "Хотите также?",
        orderTitle: "Получите неделю доступа к курсу всего за",
        orderText: "и обретите рельефный пресс уже сейчас!",
        orderPrice1: "Доступ по акции<sup>*</sup>",
        orderPrice2: "Всего за",
        timerText: "До конца Акции:"
    },
    en: {
        mainScreenTitle1: "Pump up ",
        mainScreenTitle2: "your abs ",
        mainScreenTitle3: "from the comfort of your own home",
        mainScreenSubtitle1: "with a 30-day ",
        mainScreenSubtitle2: "online course",
        mainScreenBtn: "Try it",
        mainScreenBtnText1: "First week of class ",
        mainScreenBtnText2: "for only",
        mainScreenListSpan: "If you are:",
        mainScreenListItem1: "Tired of hiding your beer belly",
        mainScreenListItem2: "Want to build rock-hard abs",
        mainScreenListItem3: "Want to attract women's eyes",
        mainScreenListItem4: "Want to feel more confident",
        mainScreenListItem5: "Want to become stronger and more resilient",
        mainScreenSuptitle: "Online training",
        mainScreenOnlineTitle: "Relief abs",
        mainScreenOnlineSubtitle: "is what you need!",
        profitTitle1: "In just ",
        profitTitle2: "30 days",
        profitTitle3: " you will:",
        profitItemTitle1: "Improve your well-being and mood",
        profitItemText1: "Sport has a positive effect on the emotional state of a person and helps to produce joy hormones",
        profitItemTitle2: "Become stronger and more resilient",
        profitItemText2: "With regular exercise, you will notice a big change in your physical shape",
        profitItemTitle3: "Gain a beautiful relief",
        profitItemText3: "Without a thick layer of fat, thanks to a competent and complex approach",
        profitItemTitle4: "Feel more confident",
        profitItemText4: "Thanks to the spectacular appearance, strength and attention of the opposite sex ;)",
        profitPersonalTitle: "In your personal cabinet you will find:",
        profitPersonalLabel: "Everything for top results!",
        profitPersonalItemText1: "Effective trainings",
        profitPersonalItemText2: "For visible results",
        profitPersonalItemText3: "Monthly nutrition plan",
        profitPersonalItemText4: "For a comprehensive approach",
        profitPersonalItemText5: "Tips and lectures from trainers",
        profitPersonalItemText6: "For training and motivation",
        tryTitle: "Pump up your hard abs now!",
        trySubtitle: "Try the first week of workouts for only",
        tryBtn: "Try it",
        startTitle1: "Now ",
        startTitle2: "is the best time ",
        startTitle3: "to get started!",
        startStepTitle1: "Pay for access to the course",
        startStepTitle2: "Log in to your personal account",
        startStepTitle3: "Study anytime, anywhere",
        startStepTitle4: "Get high on results and catch the admiring glances of women.",
        orderSubtitle: "Want the same?",
        orderTitle: "Get a week's access to the course for just",
        orderText: "and get defined abs now!",
        orderPrice1: "Promotional Access<sup>*</sup>",
        orderPrice2: "Only ",
        timerText: "Till end of Promotion:"
    },
    es: {
        mainScreenTitle1: "Mejora tus ",
        mainScreenTitle2: "abdominales ",
        mainScreenTitle3: "desde la comodidad de tu casa",
        mainScreenSubtitle1: "con un curso online ",
        mainScreenSubtitle2: "de 30 días",
        mainScreenBtn: "Prueba",
        mainScreenBtnText1: "Primera semana de clases ",
        mainScreenBtnText2: "por sólo",
        mainScreenListSpan: "Si estás:",
        mainScreenListItem1: "Cansado de esconder tu barriga cervecera",
        mainScreenListItem2: "Quieres construir abdominales duros como rocas",
        mainScreenListItem3: "Quieres atraer las miradas de las mujeres",
        mainScreenListItem4: "Quieres sentirte más seguro de ti mismo",
        mainScreenListItem5: "Quieres ser más fuerte y resistente",
        mainScreenSuptitle: "Entrenamiento en línea",
        mainScreenOnlineTitle: '"Abdominales de infarto"',
        mainScreenOnlineSubtitle: "lo que necesitas",
        profitTitle1: "En sólo ",
        profitTitle2: "30 días",
        profitTitle3: " conseguirás:",
        profitItemTitle1: "Mejorar tu bienestar y estado de ánimo",
        profitItemText1: "El deporte tiene un efecto positivo en tu estado emocional y ayuda a producir hormonas de la felicidad",
        profitItemTitle2: "Serás más fuerte y resistente",
        profitItemText2: "Con el ejercicio regular, notará un gran cambio en su forma física",
        profitItemTitle3: "Consigue un bonito relieve",
        profitItemText3: "Sin una gruesa capa de grasa, gracias a un enfoque competente e integral",
        profitItemTitle4: "Siéntase más seguro de sí mismo",
        profitItemText4: "Gracias a un aspecto espectacular, fuerza y atención del sexo opuesto ;)",
        profitPersonalTitle: "En su gabinete personal encontrará:",
        profitPersonalLabel: "Todo para obtener los mejores resultados",
        profitPersonalItemText1: "Entrenamientos eficaces",
        profitPersonalItemText2: "Para resultados visibles",
        profitPersonalItemText3: "Plan de nutrición mensual",
        profitPersonalItemText4: "Para un enfoque integral",
        profitPersonalItemText5: "Consejos y conferencias de los entrenadores",
        profitPersonalItemText6: "Para más información y motivación",
        tryTitle: "¡Aumenta tus abdominales ahora!",
        trySubtitle: "Prueba la primera semana de entrenamientos por sólo ",
        tryBtn: "Pruébalo",
        startTitle1: "¡Ahora es ",
        startTitle2: "el mejor momento ",
        startTitle3: "para empezar!",
        startStepTitle1: "Paga para acceder al curso",
        startStepTitle2: "Accede a tu cuenta personal",
        startStepTitle3: "Estudia en cualquier momento y lugar",
        startStepTitle4: "Obtén grandes resultados y atrae las miradas de admiración de las mujeres",
        orderSubtitle: "¿Quieres lo mismo?",
        orderTitle: "Consigue una semana de acceso al curso por sólo",
        orderText: "y consigue unos abdominales definidos ¡ahora!",
        orderPrice1: "Acceso Promocional<sup>*</sup>",
        orderPrice2: "Sólo",
        timerText: "Hasta el final de la Promoción:"
    }
};
